### ISSUE TITLE
中断功能，为开发"需要连续对话的功能"提供便捷的工具

### ISSUE THREAD

**Issue by drinkal** [drinkal/Mirai-js#2]
类似这个 `Python` Mirai 项目 - [GraiaProject](https://github.com/GraiaProject/Application) 的这个功能 [文档](https://graia-document.vercel.app/docs/broadcast-control/bcc-interrupt)

相关 `commit`: GraiaProject/Application@136053f534dc59cb02d0aadccd261dbf4d000bbb

**Comment by GreyElaina** [comment]
不好意思.....我觉得一次回调不够用.

**Comment by drinkal** [comment]
> 不好意思.....我觉得一次回调不够用.

这个 issue 还没解决呢。

一次回调是为了做一些简单的功能，例如触发后，注册一个带有过滤该 qq 中间件的一次回调。

当然如果对于多个线性对话，也可以不断地深层嵌套注册，但是问题在于这样会导致多个线性对话变成回调地狱。

我在考虑 ES6 的 generator 函数，因为他易于表示状态机，这尤其对实现菜单这种需求非常有用。

我还在参考 promise 实现的异步，和 thunk 对 generator 的操作实现的异步，看看能不能找到什么更优雅的解决方案。

**Comment by drinkal** [comment]
> 不好意思.....我觉得一次回调不够用.

实际上我们完全可以直接要求开发者来写出这样的代码，因为 js 拥有完善的异步特性和相关的语法糖，但是这并不足够简单，我还是想通过框架来提供这种功能，不过暂时没什么好的想法。


```js

bot.on('FriendMessage', async data => {
    // ...

    // 触发连续对话
    if (/* condition */) {

        // 第一阶段的对话
        let result = await new Promise((resolve) => {
            bot.one('FriendMessage', new Middleware()
                .friendFilter(data.sender.id)
                .done(innerData => {
                    // ...
                    resolve(/* 本阶段对话的结果 */);
                }));
        });

        // 做一些状态的抉择

        // 第二阶段的对话
        result = await new Promise((resolve) => {
            bot.one('FriendMessage', new Middleware()
                .friendFilter(data.sender.id)
                .done(innerData => {
                    // ...
                    resolve(/* 本阶段对话的结果 */);
                }));
        });


        // ...
    }
});

```

**Comment by GreyElaina** [comment]
py 表示非常羡慕 js 的 promise.

**Comment by drinkal** [comment]
> py 表示非常羡慕 js 的 promise.

我刚刚实现了一个 `Waiter` 类，他作为每个 `Bot` 实例维护的内部类实例出现。

我参考了 `graia` 的中断接口，然后为开发者提供了这样一个功能，即在异步代码中同步等待下一条消息，这就相当于提供了线性处理对话的途径了，剩下的对消息的判断，状态转移等都是同步逻辑，就都是开发者的工作了，至于等待的消息种类、好友、群组、成员等，可以通过一些框架预定义的中间件来过滤。相关文档已经更新了。

尽可能少地向等待器中封装涉及判断的功能，我认为这样可以尽可能地把自由度开放出去。

将来这个 `Waiter` 类也许还会扩展一些功能。
